# Generated by Django 5.0.4 on 2024-05-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard', '0002_cadastraocartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastraocartao',
            name='lote',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
