# Generated by Django 5.0.4 on 2024-05-07 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard', '0003_cadastraocartao_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('data', models.CharField(blank=True, max_length=8)),
                ('numero', models.CharField(blank=True, max_length=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
